on:
  workflow_dispatch:
  push:
    tags: ['*']

permissions:
  contents: read

jobs:
  compile-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build jar
        run: gradle shadowJar
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: libsodiumpasswordhashprovider
          path: build/libs/libsodiumpasswordhashprovider-*.jar
