on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build jar
        run: gradle shadowJar
      - name: Move jar to release directory
        run: mkdir to-release && mv build/libs/libsodiumpasswordhashprovider-*.jar to-release/
      - name: Create draft release
        uses: MaciejSzczurek/release-action@main
        with:
          assets-directory: to-release
